/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.registration.administrator;

import student.registration.dataentry.*;
import student.registration.teacher.*;
import student.registration.*;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import student.registration.utils.DBConnect;

/**
 *
 * @author Elvis
 */
public class AdministratorLandingPage extends javax.swing.JFrame {

    private String retrievedUsername = null;

    /**
     * Creates new form StudentLandingPage
     */
    public AdministratorLandingPage(String username) {
        this.retrievedUsername = username;
        initComponents();
        // populateMarksTable(stNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftSplitPanel = new javax.swing.JPanel();
        subjectsBtn = new javax.swing.JButton();
        accountBtn = new javax.swing.JButton();
        moreBtn = new javax.swing.JButton();
        rightSplitPanel = new javax.swing.JPanel();
        studentReportPanel = new javax.swing.JPanel();
        updatePanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        stAcTitle1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        searchType_student_combo_2 = new javax.swing.JComboBox();
        searchField_student_field_2 = new javax.swing.JTextField();
        searchBtn_student_button_2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        filterType_combo = new javax.swing.JComboBox();
        filterField = new javax.swing.JTextField();
        filterSearchBtn = new javax.swing.JButton();
        filterError = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        marksTable_report = new javax.swing.JTable();
        manageUsersPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lecNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        accountListTable = new javax.swing.JTable();
        usernameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addAccountBtn = new javax.swing.JButton();
        updateAccountBtn = new javax.swing.JButton();
        deleteAccountBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        error_message = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox();
        passwordField = new javax.swing.JPasswordField();
        changePasswordCardPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        oldPassField = new javax.swing.JPasswordField();
        newPassField = new javax.swing.JPasswordField();
        confirmField = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management Portal");
        setName("container"); // NOI18N
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleLabel.setText("Student Portal");
        getContentPane().add(titleLabel, java.awt.BorderLayout.CENTER);

        jSplitPane1.setDividerLocation(150);

        leftSplitPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        leftSplitPanel.setMaximumSize(new java.awt.Dimension(150, 309));
        leftSplitPanel.setMinimumSize(new java.awt.Dimension(150, 309));

        subjectsBtn.setText("Reports");
        subjectsBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        subjectsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectsBtnActionPerformed(evt);
            }
        });

        accountBtn.setText("Manage Users");
        accountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBtnActionPerformed(evt);
            }
        });

        moreBtn.setText("More");
        moreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftSplitPanelLayout = new javax.swing.GroupLayout(leftSplitPanel);
        leftSplitPanel.setLayout(leftSplitPanelLayout);
        leftSplitPanelLayout.setHorizontalGroup(
            leftSplitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSplitPanelLayout.createSequentialGroup()
                .addGroup(leftSplitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moreBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subjectsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftSplitPanelLayout.setVerticalGroup(
            leftSplitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSplitPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(subjectsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(moreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(leftSplitPanel);

        rightSplitPanel.setLayout(new java.awt.CardLayout());

        updatePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 53, 53, 53));

        stAcTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stAcTitle1.setText("Student Academic Reports");

        jLabel13.setText("Search by");

        searchType_student_combo_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student No", "Subject Code" }));
        searchType_student_combo_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchType_student_combo_2ActionPerformed(evt);
            }
        });

        searchBtn_student_button_2.setText("Search");
        searchBtn_student_button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn_student_button_2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Filter By");

        filterType_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semester" }));
        filterType_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterType_comboActionPerformed(evt);
            }
        });

        filterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterFieldActionPerformed(evt);
            }
        });

        filterSearchBtn.setText("Search");
        filterSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterSearchBtnActionPerformed(evt);
            }
        });

        filterError.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(stAcTitle1))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(searchType_student_combo_2, 0, 111, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(searchField_student_field_2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(filterType_combo, 0, 111, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(filterError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filterField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBtn_student_button_2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(filterSearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(529, 529, 529))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stAcTitle1)
                .addGap(37, 37, 37)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField_student_field_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn_student_button_2)
                    .addComponent(searchType_student_combo_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterType_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterSearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filterError, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE))
        );

        jScrollPane5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        marksTable_report.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        marksTable_report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Student No", "Subject Code", "Internal ", "External", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        marksTable_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marksTable_reportMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(marksTable_report);

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout studentReportPanelLayout = new javax.swing.GroupLayout(studentReportPanel);
        studentReportPanel.setLayout(studentReportPanelLayout);
        studentReportPanelLayout.setHorizontalGroup(
            studentReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentReportPanelLayout.createSequentialGroup()
                .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        studentReportPanelLayout.setVerticalGroup(
            studentReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentReportPanelLayout.createSequentialGroup()
                .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 286, Short.MAX_VALUE))
        );

        rightSplitPanel.add(studentReportPanel, "card_report_panel");

        manageUsersPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        manageUsersPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lecNameLabel.setText("Username");

        jLabel3.setText("Role");

        accountListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Username ", "User ID", "Password", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        accountListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountListTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(accountListTable);
        if (accountListTable.getColumnModel().getColumnCount() > 0) {
            accountListTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            accountListTable.getColumnModel().getColumn(0).setMaxWidth(50);
            accountListTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            accountListTable.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Account List");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Accounts");

        addAccountBtn.setText("Add");
        addAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountBtnActionPerformed(evt);
            }
        });

        updateAccountBtn.setText("Update");
        updateAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAccountBtnActionPerformed(evt);
            }
        });

        deleteAccountBtn.setText("Delete");
        deleteAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(addAccountBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateAccountBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteAccountBtn)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAccountBtn)
                    .addComponent(updateAccountBtn)
                    .addComponent(deleteAccountBtn)))
        );

        jLabel12.setText("Password");

        error_message.setForeground(new java.awt.Color(255, 0, 0));

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator", "Student", "Teacher", "Data Entry Operator" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lecNameLabel)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel12))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(usernameField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roleComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 166, Short.MAX_VALUE)
                                    .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lecNameLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        manageUsersPanel.add(jPanel1, java.awt.BorderLayout.LINE_START);

        rightSplitPanel.add(manageUsersPanel, "manage_users_card");
        manageUsersPanel.getAccessibleContext().setAccessibleName("");

        changePasswordCardPanel.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 53, 1, 53));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Update Account Information");

        jLabel8.setText("Change Password");

        jLabel9.setText("Old Password");

        jLabel10.setText("New Password");

        saveBtn.setText("Save");

        jLabel11.setText("Confirm Password");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(saveBtn))
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(oldPassField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addComponent(newPassField)
                                .addComponent(confirmField)))))
                .addContainerGap(639, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(oldPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(confirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(saveBtn)
                .addContainerGap(533, Short.MAX_VALUE))
        );

        changePasswordCardPanel.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        rightSplitPanel.add(changePasswordCardPanel, "card_change_password");

        jSplitPane1.setRightComponent(rightSplitPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.PAGE_START);

        jMenuBar1.setName("menuBar"); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setText("Sign Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setText("About us");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectsBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) rightSplitPanel.getLayout();
        card.show(rightSplitPanel, "card_report_panel");
        
    }//GEN-LAST:event_subjectsBtnActionPerformed

    private void moreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreBtnActionPerformed

        CardLayout card = (CardLayout) rightSplitPanel.getLayout();
        card.show(rightSplitPanel, "card_change_password");


    }//GEN-LAST:event_moreBtnActionPerformed

    private void accountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) rightSplitPanel.getLayout();
        card.show(rightSplitPanel, "manage_users_card");
        DefaultTableModel model = (DefaultTableModel) accountListTable.getModel();
        
        DBConnect.TableData accountData = new DBConnect().getAllUsers();
        
       
        Object[][] row = accountData.getcolData();
        System.out.println("" + accountData.getcolData().length + " columns");
        for (int i = 0; i < accountData.getRowCount(); i++) {

            model.addRow(new Object[]{model.getRowCount()+1, row[i][0], row[i][1], row[i][2], row[i][3]});
            System.out.println("added " + row[i][3]);
        }
    }//GEN-LAST:event_accountBtnActionPerformed

    private void accountListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountListTableMouseClicked
        
        DefaultTableModel model = (DefaultTableModel) accountListTable.getModel();
        usernameField.setText(model.getValueAt(accountListTable.getSelectedRow(), 1).toString());
        passwordField.setText(model.getValueAt(accountListTable.getSelectedRow(), 4).toString());
        
        
        
    }//GEN-LAST:event_accountListTableMouseClicked

    private void searchType_student_combo_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchType_student_combo_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchType_student_combo_2ActionPerformed

    private void searchBtn_student_button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn_student_button_2ActionPerformed

        String searchType = searchType_student_combo_2.getSelectedItem().toString();
        String searchTerm = searchField_student_field_2.getText();
        filterError.setText("");

        DefaultTableModel model = (DefaultTableModel) marksTable_report.getModel();
        new DBConnect().deleteAllRows(model);
        DBConnect.TableData tableData = null;
        if (searchType.equals("Student No")) { //Student No, Subject Code  Student No, Subject Code

            tableData =   new DBConnect().studentMarks_by_enrol_no(searchTerm);
        } else if (searchType.equals("Subject Code")) {

            tableData =  new DBConnect().studentMarks_by_subject(searchTerm);
        } else {
            System.out.println("Error with marksTable_teacher search term");
        }

        Object[][] row = tableData.getcolData();
        System.out.println("" + tableData.getcolData().length + " columns and "+tableData.getRowCount()+" rows");
        for (int i = 0; i < tableData.getRowCount(); i++) {

            model.addRow(new Object[]{row[i][0], row[i][1], row[i][2], row[i][3], row[i][4], row[i][5]});
            System.out.println("added " + row[i][3]);
        }

    }//GEN-LAST:event_searchBtn_student_button_2ActionPerformed

    private void marksTable_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marksTable_reportMouseClicked
        

    }//GEN-LAST:event_marksTable_reportMouseClicked

    private void deleteAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountBtnActionPerformed
        error_message.setText("");
        DefaultTableModel model = (DefaultTableModel) accountListTable.getModel();
        if (accountListTable.getSelectedRow() != -1) {

            model.removeRow(accountListTable.getSelectedRow());
            String username = usernameField.getText().toString();
            new DBConnect().deleteAccount(accountListTable.getSelectedRow());

        } else {
            if (accountListTable.getRowCount() == 0) {
                error_message.setText("Table is empty");
            } else {
                error_message.setText("You must select a student.");
            }
        }
    }//GEN-LAST:event_deleteAccountBtnActionPerformed

    private void updateAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAccountBtnActionPerformed
        error_message.setText("");
        DefaultTableModel model = (DefaultTableModel) accountListTable.getModel();
        String username = usernameField.getText().toString();
        String password = passwordField.getText().toString();
        String role = roleComboBox.getSelectedItem().toString();
        
        if (accountListTable.getSelectedRow() != -1) {

            model.setValueAt(username, accountListTable.getSelectedRow(), 1);
            model.setValueAt("******", accountListTable.getSelectedRow(), 2);
            model.setValueAt(role, accountListTable.getSelectedRow(), 3);
            
            new DBConnect().updateAccount(accountListTable.getSelectedRow()+1, username, password, role);

        } else {
            if (accountListTable.getRowCount() == 0) {
                error_message.setText("Table is empty");
            } else {
                error_message.setText("You must select a student.");
            }
        }
    }//GEN-LAST:event_updateAccountBtnActionPerformed

    private void addAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountBtnActionPerformed
        error_message.setText("");
        DefaultTableModel model = (DefaultTableModel) accountListTable.getModel();
        String username = usernameField.getText().toString();
        String password = passwordField.getText().toString();
        String role = roleComboBox.getSelectedItem().toString();
        

        if (!(username.trim().equals("")) && !(password.trim().equals("")) && !(role.trim().equals("")) ) {
            String dummypass = "*******";
            model.addRow(new Object[]{model.getRowCount()+1, username,model.getRowCount()+1, dummypass, role});
            new DBConnect().addUser(username, password, role);
        } else {

            error_message.setText("Fill in all fields.");
        }
    }//GEN-LAST:event_addAccountBtnActionPerformed

    private void filterType_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterType_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterType_comboActionPerformed

    private void filterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterFieldActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void filterSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterSearchBtnActionPerformed
        
        String searchType = searchType_student_combo_2.getSelectedItem().toString();
        String searchTerm = searchField_student_field_2.getText();
        String filterTerm = filterField.getText();
        if(!filterTerm.equals("")){
            filterError.setText("Filters not yet supported!");
        }
        DefaultTableModel model = (DefaultTableModel) marksTable_report.getModel();
        new DBConnect().deleteAllRows(model);
        DBConnect.TableData tableData = null;
        if (searchType.equals("Student No")) { //Student No, Subject Code  Student No, Subject Code

            tableData =   new DBConnect().studentMarks_by_enrol_no(searchTerm);
        } else if (searchType.equals("Subject Code")) {

            tableData =  new DBConnect().studentMarks_by_subject(searchTerm);
        } else {
            System.out.println("Error with marksTable_teacher search term");
        }

        Object[][] row = tableData.getcolData();
        System.out.println("" + tableData.getcolData().length + " columns and "+tableData.getRowCount()+" rows");
        for (int i = 0; i < tableData.getRowCount(); i++) {

            model.addRow(new Object[]{row[i][0], row[i][1], row[i][2], row[i][3], row[i][4], row[i][5]});
            System.out.println("added " + row[i][3]);
        }
    }//GEN-LAST:event_filterSearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEntryLandingPage("dataentry").setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountBtn;
    private javax.swing.JTable accountListTable;
    private javax.swing.JButton addAccountBtn;
    private javax.swing.JPanel changePasswordCardPanel;
    private javax.swing.JPasswordField confirmField;
    private javax.swing.JButton deleteAccountBtn;
    private javax.swing.JLabel error_message;
    private javax.swing.JLabel filterError;
    private javax.swing.JTextField filterField;
    private javax.swing.JButton filterSearchBtn;
    private javax.swing.JComboBox filterType_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lecNameLabel;
    private javax.swing.JPanel leftSplitPanel;
    private javax.swing.JPanel manageUsersPanel;
    private javax.swing.JTable marksTable_report;
    private javax.swing.JButton moreBtn;
    private javax.swing.JPasswordField newPassField;
    private javax.swing.JPasswordField oldPassField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel rightSplitPanel;
    private javax.swing.JComboBox roleComboBox;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn_student_button_2;
    private javax.swing.JTextField searchField_student_field_2;
    private javax.swing.JComboBox searchType_student_combo_2;
    private javax.swing.JLabel stAcTitle1;
    private javax.swing.JPanel studentReportPanel;
    private javax.swing.JButton subjectsBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateAccountBtn;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables

    private void populateEditStudentTable() {
        DBConnect.TableData tableData = new DBConnect().getAllStudents();
        DefaultTableModel model = (DefaultTableModel) accountListTable.getModel();
        Object[][] row = tableData.getcolData();
        System.out.println("" + tableData.getcolData().length + " columns");
        for (int i = 0; i < tableData.getRowCount(); i++) {

            model.addRow(new Object[]{model.getRowCount()+1, row[i][0], row[i][1], row[i][4], row[i][3], row[i][2]});
            System.out.println("added " + row[i][3]);
        }
    }
}
