/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.registration.dataentry;

import student.registration.teacher.*;
import student.registration.*;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import student.registration.utils.DBConnect;

/**
 *
 * @author Elvis
 */
public class DataEntryLandingPage extends javax.swing.JFrame {

    private String retrievedUsername = null;

    /**
     * Creates new form StudentLandingPage
     */
    public DataEntryLandingPage(String username) {
        this.retrievedUsername = username;
        initComponents();
        // populateMarksTable(stNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftSplitPanel = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        subjectsBtn = new javax.swing.JButton();
        moreBtn = new javax.swing.JButton();
        accountBtn = new javax.swing.JButton();
        rightSplitPanel = new javax.swing.JPanel();
        updateSubjectCardPanel = new javax.swing.JPanel();
        updatePanel_subject = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        stAcTitle2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        searchType_subject = new javax.swing.JComboBox();
        searchBar_subject = new javax.swing.JTextField();
        searchBtn_subject = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        editCombo_subject = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        updateField_subject = new javax.swing.JTextField();
        updateBtn_subject = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        subjectTable_dataenty = new javax.swing.JTable();
        changePasswordCardPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        oldPassField = new javax.swing.JPasswordField();
        newPassField = new javax.swing.JPasswordField();
        confirmField = new javax.swing.JPasswordField();
        moreCardPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lecNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        editStudentTable = new javax.swing.JTable();
        nameField = new javax.swing.JTextField();
        enrollmentField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addStudentBtn = new javax.swing.JButton();
        updateStudent = new javax.swing.JButton();
        deleteStudent = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        dob_student = new javax.swing.JTextField();
        error_message = new javax.swing.JLabel();
        updateResultsCardPanel = new javax.swing.JPanel();
        updatePanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        stAcTitle1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        searchType_student_combo_2 = new javax.swing.JComboBox();
        searchField_student_field_2 = new javax.swing.JTextField();
        searchBtn_student_button_2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        enrolNo_Field = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        internalField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        externalField = new javax.swing.JTextField();
        updateBtn_marks = new javax.swing.JButton();
        addMarksBtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        subjectCodeField = new javax.swing.JTextField();
        errorMessage = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        marksTable_dataentry = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management Portal");
        setName("container"); // NOI18N
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleLabel.setText("Student Portal");
        getContentPane().add(titleLabel, java.awt.BorderLayout.CENTER);

        jSplitPane1.setDividerLocation(150);

        leftSplitPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        leftSplitPanel.setMaximumSize(new java.awt.Dimension(150, 309));
        leftSplitPanel.setMinimumSize(new java.awt.Dimension(150, 309));

        updateBtn.setText("Update Results");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        subjectsBtn.setText("Subjects");
        subjectsBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        subjectsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectsBtnActionPerformed(evt);
            }
        });

        moreBtn.setText("More");
        moreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreBtnActionPerformed(evt);
            }
        });

        accountBtn.setText("Change Password");
        accountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftSplitPanelLayout = new javax.swing.GroupLayout(leftSplitPanel);
        leftSplitPanel.setLayout(leftSplitPanelLayout);
        leftSplitPanelLayout.setHorizontalGroup(
            leftSplitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSplitPanelLayout.createSequentialGroup()
                .addGroup(leftSplitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subjectsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moreBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftSplitPanelLayout.setVerticalGroup(
            leftSplitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSplitPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(subjectsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(accountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(moreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(leftSplitPanel);

        rightSplitPanel.setLayout(new java.awt.CardLayout());

        updateSubjectCardPanel.setEnabled(false);
        updateSubjectCardPanel.setMaximumSize(new java.awt.Dimension(1000, 1000));
        updateSubjectCardPanel.setOpaque(false);
        updateSubjectCardPanel.setRequestFocusEnabled(false);
        updateSubjectCardPanel.setVerifyInputWhenFocusTarget(false);
        updateSubjectCardPanel.setLayout(new java.awt.BorderLayout());

        updatePanel_subject.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 53, 53, 53));
        updatePanel_subject.setMaximumSize(new java.awt.Dimension(1000, 1000));
        updatePanel_subject.setPreferredSize(new java.awt.Dimension(911, 725));

        stAcTitle2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stAcTitle2.setText("Subject Information");

        jLabel14.setText("Search by");

        searchType_subject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Subject Name", "Subject Code" }));

        searchBtn_subject.setText("Search");
        searchBtn_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn_subjectActionPerformed(evt);
            }
        });

        editCombo_subject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Subject Name", "Subject Code", "Semester" }));

        jLabel15.setText("Select field to update");

        updateBtn_subject.setText("Update");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(editCombo_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateField_subject, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(updateBtn_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateField_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCombo_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn_subject))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(stAcTitle2)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(searchType_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchBar_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchBtn_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stAcTitle2)
                .addGap(37, 37, 37)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBar_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn_subject)
                    .addComponent(searchType_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        subjectTable_dataenty.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        subjectTable_dataenty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Subject Name", "Subject Code", "Semester"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(subjectTable_dataenty);
        if (subjectTable_dataenty.getColumnModel().getColumnCount() > 0) {
            subjectTable_dataenty.getColumnModel().getColumn(0).setPreferredWidth(50);
            subjectTable_dataenty.getColumnModel().getColumn(0).setMaxWidth(50);
            subjectTable_dataenty.getColumnModel().getColumn(1).setPreferredWidth(150);
            subjectTable_dataenty.getColumnModel().getColumn(1).setMaxWidth(150);
            subjectTable_dataenty.getColumnModel().getColumn(2).setPreferredWidth(100);
            subjectTable_dataenty.getColumnModel().getColumn(2).setMaxWidth(100);
            subjectTable_dataenty.getColumnModel().getColumn(3).setPreferredWidth(150);
            subjectTable_dataenty.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        javax.swing.GroupLayout updatePanel_subjectLayout = new javax.swing.GroupLayout(updatePanel_subject);
        updatePanel_subject.setLayout(updatePanel_subjectLayout);
        updatePanel_subjectLayout.setHorizontalGroup(
            updatePanel_subjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanel_subjectLayout.createSequentialGroup()
                .addGroup(updatePanel_subjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 427, Short.MAX_VALUE))
        );
        updatePanel_subjectLayout.setVerticalGroup(
            updatePanel_subjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanel_subjectLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
        );

        updateSubjectCardPanel.add(updatePanel_subject, java.awt.BorderLayout.CENTER);

        rightSplitPanel.add(updateSubjectCardPanel, "update_subject_card");

        changePasswordCardPanel.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 53, 1, 53));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Update Account Information");

        jLabel8.setText("Change Password");

        jLabel9.setText("Old Password");

        jLabel10.setText("New Password");

        saveBtn.setText("Save");

        jLabel11.setText("Confirm Password");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(saveBtn))
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(oldPassField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addComponent(newPassField)
                                .addComponent(confirmField)))))
                .addContainerGap(639, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(oldPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(confirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(saveBtn)
                .addContainerGap(533, Short.MAX_VALUE))
        );

        changePasswordCardPanel.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        rightSplitPanel.add(changePasswordCardPanel, "card_change_password");

        moreCardPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        moreCardPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lecNameLabel.setText("Fullname");

        jLabel3.setText("Enrollment No.");

        jLabel4.setText("Address");

        jLabel5.setText("DOB");

        editStudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Fullname", "Enrol. No", "Year", "Address", "DOB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        editStudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editStudentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(editStudentTable);
        if (editStudentTable.getColumnModel().getColumnCount() > 0) {
            editStudentTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            editStudentTable.getColumnModel().getColumn(0).setMaxWidth(50);
            editStudentTable.getColumnModel().getColumn(1).setPreferredWidth(250);
            editStudentTable.getColumnModel().getColumn(1).setMaxWidth(250);
            editStudentTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Students List");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Students");

        addStudentBtn.setText("Add");
        addStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBtnActionPerformed(evt);
            }
        });

        updateStudent.setText("Update");
        updateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentActionPerformed(evt);
            }
        });

        deleteStudent.setText("Delete");
        deleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(addStudentBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteStudent)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentBtn)
                    .addComponent(updateStudent)
                    .addComponent(deleteStudent)))
        );

        jLabel12.setText("Year");

        error_message.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lecNameLabel)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(error_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addressField)
                                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(dob_student)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(enrollmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(yearField))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lecNameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(enrollmentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dob_student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(504, Short.MAX_VALUE))
        );

        moreCardPanel.add(jPanel1, java.awt.BorderLayout.LINE_START);

        rightSplitPanel.add(moreCardPanel, "more_manage_students_card");
        moreCardPanel.getAccessibleContext().setAccessibleName("");

        updatePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 53, 53, 53));

        stAcTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stAcTitle1.setText("Student Academic Record");

        jLabel13.setText("Search by");

        searchType_student_combo_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student No", "Subject Code" }));
        searchType_student_combo_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchType_student_combo_2ActionPerformed(evt);
            }
        });

        searchBtn_student_button_2.setText("Search");
        searchBtn_student_button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn_student_button_2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Select field to update");

        jLabel16.setText("Internal Marks");

        jLabel17.setText("Enrolment No");

        jLabel18.setText("External Marks");

        externalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externalFieldActionPerformed(evt);
            }
        });

        updateBtn_marks.setText("Update");
        updateBtn_marks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn_marksActionPerformed(evt);
            }
        });

        addMarksBtn.setText("Add");
        addMarksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMarksBtnActionPerformed(evt);
            }
        });

        jLabel19.setText("Subject Code");

        subjectCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCodeFieldActionPerformed(evt);
            }
        });

        errorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enrolNo_Field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internalField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addMarksBtn))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateBtn_marks)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(externalField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(subjectCodeField))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(enrolNo_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(subjectCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(internalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(externalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateBtn_marks)
                    .addComponent(addMarksBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(searchType_student_combo_2, 0, 111, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(searchField_student_field_2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn_student_button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(529, 529, 529))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(stAcTitle1))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stAcTitle1)
                .addGap(37, 37, 37)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField_student_field_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn_student_button_2)
                    .addComponent(searchType_student_combo_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jScrollPane5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        marksTable_dataentry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        marksTable_dataentry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Student No", "Subject Code", "Internal ", "External", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        marksTable_dataentry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marksTable_dataentryMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(marksTable_dataentry);

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout updateResultsCardPanelLayout = new javax.swing.GroupLayout(updateResultsCardPanel);
        updateResultsCardPanel.setLayout(updateResultsCardPanelLayout);
        updateResultsCardPanelLayout.setHorizontalGroup(
            updateResultsCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateResultsCardPanelLayout.createSequentialGroup()
                .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        updateResultsCardPanelLayout.setVerticalGroup(
            updateResultsCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateResultsCardPanelLayout.createSequentialGroup()
                .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 414, Short.MAX_VALUE))
        );

        rightSplitPanel.add(updateResultsCardPanel, "card_update_results");

        jSplitPane1.setRightComponent(rightSplitPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.PAGE_START);

        jMenuBar1.setName("menuBar"); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setText("Sign Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setText("About us");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectsBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) rightSplitPanel.getLayout();
        card.show(rightSplitPanel, "update_subject_card");
        
    }//GEN-LAST:event_subjectsBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

        CardLayout card = (CardLayout) rightSplitPanel.getLayout();
        card.show(rightSplitPanel, "update_results_card");


    }//GEN-LAST:event_updateBtnActionPerformed

    private void moreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreBtnActionPerformed
        populateEditStudentTable();
        CardLayout card = (CardLayout) rightSplitPanel.getLayout();
        card.show(rightSplitPanel, "more_manage_students_card");

    }//GEN-LAST:event_moreBtnActionPerformed

    private void accountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) rightSplitPanel.getLayout();
        card.show(rightSplitPanel, "card_change_password");
    }//GEN-LAST:event_accountBtnActionPerformed

    private void searchBtn_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn_subjectActionPerformed
        String searchType = searchType_subject.getSelectedItem().toString();
        String searchTerm = searchBar_subject.getText();
        
        DefaultTableModel model = (DefaultTableModel) subjectTable_dataenty.getModel();
        new DBConnect().deleteAllRows(model);
         DBConnect.TableData tableData = null;
        if (searchType.equals("Subject Name")) { //Subject Name, Subject Code
              tableData =   new DBConnect().searchSubject_by_name(searchTerm);
        } else if (searchType.equals("Subject Code")) {
              tableData =  new DBConnect().searchSubject_by_code(searchTerm);
        }
        
        Object[][] row = tableData.getcolData();
        System.out.println("" + tableData.getcolData().length + " columns");
        for (int i = 0; i < tableData.getRowCount(); i++) {

            model.addRow(new Object[]{row[i][0], row[i][1], row[i][2], row[i][3]});
            System.out.println("added " + row[i][3]);
        }

    }//GEN-LAST:event_searchBtn_subjectActionPerformed

    private void updateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentActionPerformed
        error_message.setText("");
        DefaultTableModel model = (DefaultTableModel) editStudentTable.getModel();
        String fullname = nameField.getText().toString();
        String enrolNo = enrollmentField.getText().toString();
        String address = addressField.getText().toString();
        String dob = dob_student.getText().toString();
        String year = yearField.getText().toString();
        if (editStudentTable.getSelectedRow() != -1) {
            
            model.setValueAt(fullname, editStudentTable.getSelectedRow(), 1);
            model.setValueAt(enrolNo, editStudentTable.getSelectedRow(), 2);
            model.setValueAt(address, editStudentTable.getSelectedRow(), 4);
            model.setValueAt(dob, editStudentTable.getSelectedRow(), 5);
            model.setValueAt(year, editStudentTable.getSelectedRow(), 3);
            new DBConnect().updateStudentInfo(editStudentTable.getSelectedRow()+1, fullname, enrolNo, year, address, dob);
                    
        } else {
            if (editStudentTable.getRowCount() == 0) {
                error_message.setText("Table is empty");
            } else {
                error_message.setText("You must select a student.");
            }
        }

    }//GEN-LAST:event_updateStudentActionPerformed

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
        error_message.setText("");
        DefaultTableModel model = (DefaultTableModel) editStudentTable.getModel();
        String fullname = nameField.getText().toString();
        String enrolNo = enrollmentField.getText().toString();
        String address = addressField.getText().toString();
        String dob = dob_student.getText().toString();
        String year = yearField.getText().toString();

        if (!(fullname.trim().equals("")) && !(enrolNo.trim().equals("")) && !(enrolNo.trim().equals("")) && !(address.trim().equals("")) && !(dob.trim().equals(""))) {
            model.addRow(new Object[]{model.getRowCount()+1, fullname, enrolNo, year, address, dob});
            new DBConnect().addStudent(fullname, enrolNo, dob, address, year);
        } else {

            error_message.setText("Fill in all fields.");
        }
    }//GEN-LAST:event_addStudentBtnActionPerformed

    private void deleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentActionPerformed
        error_message.setText("");
        DefaultTableModel model = (DefaultTableModel) editStudentTable.getModel();
        if (editStudentTable.getSelectedRow() != -1) {
            
            model.removeRow(editStudentTable.getSelectedRow());
            String enrolNo = enrollmentField.getText().toString();
            new DBConnect().deleteStudent(enrolNo);
            
        } else {
            if (editStudentTable.getRowCount() == 0) {
                error_message.setText("Table is empty");
            } else {
                error_message.setText("You must select a student.");
            }
        }
    }//GEN-LAST:event_deleteStudentActionPerformed

    private void editStudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editStudentTableMouseClicked
        
        DefaultTableModel model = (DefaultTableModel) editStudentTable.getModel();
        nameField.setText(model.getValueAt(editStudentTable.getSelectedRow(), 1).toString());
        enrollmentField.setText(model.getValueAt(editStudentTable.getSelectedRow(), 2).toString());
        addressField.setText(model.getValueAt(editStudentTable.getSelectedRow(), 4).toString());
        dob_student.setText(model.getValueAt(editStudentTable.getSelectedRow(), 3).toString());
        yearField.setText(model.getValueAt(editStudentTable.getSelectedRow(), 5).toString());
        
    }//GEN-LAST:event_editStudentTableMouseClicked

    private void searchType_student_combo_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchType_student_combo_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchType_student_combo_2ActionPerformed

    private void searchBtn_student_button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn_student_button_2ActionPerformed

        String searchType = searchType_student_combo_2.getSelectedItem().toString();
        String searchTerm = searchField_student_field_2.getText();

        DefaultTableModel model = (DefaultTableModel) marksTable_dataentry.getModel();
        new DBConnect().deleteAllRows(model);
        DBConnect.TableData tableData = null;
        if (searchType.equals("Student No")) { //Student No, Subject Code  Student No, Subject Code

            tableData =   new DBConnect().studentMarks_by_enrol_no(searchTerm);
        } else if (searchType.equals("Subject Code")) {

            tableData =  new DBConnect().studentMarks_by_subject(searchTerm);
        } else {
            System.out.println("Error with marksTable_teacher search term");
        }

        Object[][] row = tableData.getcolData();
        System.out.println("" + tableData.getcolData().length + " columns and "+tableData.getRowCount()+" rows");
        for (int i = 0; i < tableData.getRowCount(); i++) {

            model.addRow(new Object[]{row[i][0], row[i][1], row[i][2], row[i][3], row[i][4], row[i][5]});
            System.out.println("added " + row[i][3]);
        }

    }//GEN-LAST:event_searchBtn_student_button_2ActionPerformed

    private void externalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_externalFieldActionPerformed

    private void updateBtn_marksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn_marksActionPerformed
        errorMessage.setText("");

        int total = 0;
        DefaultTableModel model = (DefaultTableModel) marksTable_dataentry.getModel();
        if (marksTable_dataentry.getSelectedRow() != -1) {
            String enrol = enrolNo_Field.getText();
            String internal = internalField.getText();
            String external = externalField.getText();
            String subcode = subjectCodeField.getText();
            if(!enrol.equals("")){
                model.setValueAt(enrol, marksTable_dataentry.getSelectedRow(), 1);
                model.setValueAt(internal, marksTable_dataentry.getSelectedRow(), 3);
                model.setValueAt(external, marksTable_dataentry.getSelectedRow(), 4);
                model.setValueAt(subcode, marksTable_dataentry.getSelectedRow(), 2);
                total = Integer.parseInt(internal) + Integer.parseInt(external);
                model.setValueAt(total, marksTable_dataentry.getSelectedRow(), 5);
                new DBConnect().updateStudentMarks(enrol, internal, external, total, (total > 49), subcode);
            }else {
                errorMessage.setText("All Fields must be filled.");
            }
        } else {
            if (marksTable_dataentry.getRowCount() == 0) {
                errorMessage.setText("Search for a student first.");
            } else {
                errorMessage.setText("You must select a student.");
            }
        }
    }//GEN-LAST:event_updateBtn_marksActionPerformed

    private void addMarksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMarksBtnActionPerformed
        errorMessage.setText("");

        String enrol = enrolNo_Field.getText();
        String internal = internalField.getText();
        String external = externalField.getText();
        String subcode = subjectCodeField.getText();
        int total = Integer.parseInt(internal) + Integer.parseInt(external);
        if(!enrol.equals("") && !internal.equals("") && !external.equals("") && !subcode.equals("")){

            DefaultTableModel model = (DefaultTableModel) marksTable_dataentry.getModel();
            model.addRow(new Object[]{model.getRowCount()+1, enrol, subcode, internal, external, total});

            new DBConnect().addStudentMarks( enrol, internal, external, total, (total > 50), subcode);
        }else {
            errorMessage.setText("All Fields are required!");//All Fields are required!
        }
    }//GEN-LAST:event_addMarksBtnActionPerformed

    private void subjectCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectCodeFieldActionPerformed

    private void marksTable_dataentryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marksTable_dataentryMouseClicked
        DefaultTableModel model = (DefaultTableModel) marksTable_dataentry.getModel();
        enrolNo_Field.setText(model.getValueAt(marksTable_dataentry.getSelectedRow(), 1).toString());
        internalField.setText(model.getValueAt(marksTable_dataentry.getSelectedRow(), 3).toString());
        externalField.setText(model.getValueAt(marksTable_dataentry.getSelectedRow(), 4).toString());
        subjectCodeField.setText(model.getValueAt(marksTable_dataentry.getSelectedRow(), 2).toString());

    }//GEN-LAST:event_marksTable_dataentryMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEntryLandingPage("dataentry").setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountBtn;
    private javax.swing.JButton addMarksBtn;
    private javax.swing.JButton addStudentBtn;
    private javax.swing.JTextField addressField;
    private javax.swing.JPanel changePasswordCardPanel;
    private javax.swing.JPasswordField confirmField;
    private javax.swing.JButton deleteStudent;
    private javax.swing.JTextField dob_student;
    private javax.swing.JComboBox editCombo_subject;
    private javax.swing.JTable editStudentTable;
    private javax.swing.JTextField enrolNo_Field;
    private javax.swing.JTextField enrollmentField;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel error_message;
    private javax.swing.JTextField externalField;
    private javax.swing.JTextField internalField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lecNameLabel;
    private javax.swing.JPanel leftSplitPanel;
    private javax.swing.JTable marksTable_dataentry;
    private javax.swing.JButton moreBtn;
    private javax.swing.JPanel moreCardPanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField newPassField;
    private javax.swing.JPasswordField oldPassField;
    private javax.swing.JPanel rightSplitPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField searchBar_subject;
    private javax.swing.JButton searchBtn_student_button_2;
    private javax.swing.JButton searchBtn_subject;
    private javax.swing.JTextField searchField_student_field_2;
    private javax.swing.JComboBox searchType_student_combo_2;
    private javax.swing.JComboBox searchType_subject;
    private javax.swing.JLabel stAcTitle1;
    private javax.swing.JLabel stAcTitle2;
    private javax.swing.JTextField subjectCodeField;
    private javax.swing.JTable subjectTable_dataenty;
    private javax.swing.JButton subjectsBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateBtn_marks;
    private javax.swing.JButton updateBtn_subject;
    private javax.swing.JTextField updateField_subject;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JPanel updatePanel_subject;
    private javax.swing.JPanel updateResultsCardPanel;
    private javax.swing.JButton updateStudent;
    private javax.swing.JPanel updateSubjectCardPanel;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables

    private void populateEditStudentTable() {
        DBConnect.TableData tableData = new DBConnect().getAllStudents();
        DefaultTableModel model = (DefaultTableModel) editStudentTable.getModel();
        Object[][] row = tableData.getcolData();
        System.out.println("" + tableData.getcolData().length + " columns");
        for (int i = 0; i < tableData.getRowCount(); i++) {

            model.addRow(new Object[]{model.getRowCount()+1, row[i][0], row[i][1], row[i][4], row[i][3], row[i][2]});
            System.out.println("added " + row[i][3]);
        }
    }
}
