/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package student.registration.teacher;

import student.registration.*;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import student.registration.utils.DBConnect;

/**
 *
 * @author Elvis
 */
public class TeacherLandingPage extends javax.swing.JFrame {
    private String retrievedUsername = null;

    /**
     * Creates new form StudentLandingPage
     */
    public TeacherLandingPage(String username) {
        this.retrievedUsername = username;
        initComponents();
       // populateMarksTable(enrol_no);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftSplitPanel = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        stSearchBtn = new javax.swing.JButton();
        moreBtn = new javax.swing.JButton();
        accountBtn = new javax.swing.JButton();
        rightSplitPanel = new javax.swing.JPanel();
        stSearchCardPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        stAcTitle = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        searchType_student = new javax.swing.JComboBox();
        searchField_student = new javax.swing.JTextField();
        searchBtn_student = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        studentSearchTable = new javax.swing.JTable();
        updateResultsCardPanel = new javax.swing.JPanel();
        updatePanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        stAcTitle1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        searchType_student_combo_2 = new javax.swing.JComboBox();
        searchField_student_field_2 = new javax.swing.JTextField();
        searchBtn_student_button_2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        enrolNo_Field = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        internalField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        externalField = new javax.swing.JTextField();
        updateBtn_marks = new javax.swing.JButton();
        addMarksBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        subjectCodeField = new javax.swing.JTextField();
        errorMessage = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        marksTable_teacher = new javax.swing.JTable();
        changePasswordCardPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        oldPassField = new javax.swing.JPasswordField();
        newPassField = new javax.swing.JPasswordField();
        confirmField = new javax.swing.JPasswordField();
        informationCardPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lecNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        subjectsTable = new javax.swing.JTable();
        nameField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        subjectField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        signout_menu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management Portal");
        setName("container"); // NOI18N
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleLabel.setText("Teacher Portal");
        getContentPane().add(titleLabel, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setDividerLocation(150);

        leftSplitPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        leftSplitPanel.setMaximumSize(new java.awt.Dimension(150, 309));
        leftSplitPanel.setMinimumSize(new java.awt.Dimension(150, 309));

        updateBtn.setText("Update Results");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        stSearchBtn.setText("Student Search");
        stSearchBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        stSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stSearchBtnActionPerformed(evt);
            }
        });

        moreBtn.setText("More");
        moreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreBtnActionPerformed(evt);
            }
        });

        accountBtn.setText("Change Password");
        accountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftSplitPanelLayout = new javax.swing.GroupLayout(leftSplitPanel);
        leftSplitPanel.setLayout(leftSplitPanelLayout);
        leftSplitPanelLayout.setHorizontalGroup(
            leftSplitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSplitPanelLayout.createSequentialGroup()
                .addGroup(leftSplitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stSearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moreBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftSplitPanelLayout.setVerticalGroup(
            leftSplitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSplitPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(stSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(accountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(moreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(leftSplitPanel);

        rightSplitPanel.setLayout(new java.awt.CardLayout());

        stSearchCardPanel.setEnabled(false);
        stSearchCardPanel.setOpaque(false);
        stSearchCardPanel.setRequestFocusEnabled(false);
        stSearchCardPanel.setVerifyInputWhenFocusTarget(false);
        stSearchCardPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 53, 53, 53));

        stAcTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stAcTitle.setText("Student Academic Records");

        jLabel12.setText("Search by");

        searchType_student.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student No", "Student Name" }));

        searchBtn_student.setText("search");
        searchBtn_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn_studentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchType_student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(stAcTitle))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(searchField_student, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(searchBtn_student)))
                .addContainerGap(524, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stAcTitle)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(searchType_student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField_student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn_student))
                .addGap(27, 27, 27))
        );

        studentSearchTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 53, 1, 1));
        studentSearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Fullname", "Student No", "Batch", "Address", "DOB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentSearchTable.setMaximumSize(new java.awt.Dimension(450, 0));
        jScrollPane4.setViewportView(studentSearchTable);
        if (studentSearchTable.getColumnModel().getColumnCount() > 0) {
            studentSearchTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            studentSearchTable.getColumnModel().getColumn(0).setMaxWidth(50);
            studentSearchTable.getColumnModel().getColumn(1).setPreferredWidth(250);
            studentSearchTable.getColumnModel().getColumn(1).setMaxWidth(250);
            studentSearchTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            studentSearchTable.getColumnModel().getColumn(2).setMaxWidth(150);
            studentSearchTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            studentSearchTable.getColumnModel().getColumn(3).setMaxWidth(100);
            studentSearchTable.getColumnModel().getColumn(4).setPreferredWidth(150);
            studentSearchTable.getColumnModel().getColumn(4).setMaxWidth(150);
            studentSearchTable.getColumnModel().getColumn(5).setPreferredWidth(150);
            studentSearchTable.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        stSearchCardPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        rightSplitPanel.add(stSearchCardPanel, "card_student_search");

        updatePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 53, 53, 53));

        stAcTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stAcTitle1.setText("Student Academic Record");

        jLabel13.setText("Search by");

        searchType_student_combo_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student No", "Subject Code" }));
        searchType_student_combo_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchType_student_combo_2ActionPerformed(evt);
            }
        });

        searchBtn_student_button_2.setText("Search");
        searchBtn_student_button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn_student_button_2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Select field to update");

        jLabel15.setText("Internal Marks");

        jLabel14.setText("Enrolment No");

        jLabel16.setText("External Marks");

        externalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externalFieldActionPerformed(evt);
            }
        });

        updateBtn_marks.setText("Update");
        updateBtn_marks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn_marksActionPerformed(evt);
            }
        });

        addMarksBtn.setText("Add");
        addMarksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMarksBtnActionPerformed(evt);
            }
        });

        jLabel17.setText("Subject Code");

        subjectCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCodeFieldActionPerformed(evt);
            }
        });

        errorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enrolNo_Field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internalField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addMarksBtn))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateBtn_marks)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(externalField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(subjectCodeField))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(enrolNo_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(subjectCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(internalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(externalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn_marks)
                    .addComponent(addMarksBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(searchType_student_combo_2, 0, 111, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(searchField_student_field_2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn_student_button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(529, 529, 529))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(stAcTitle1))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stAcTitle1)
                .addGap(37, 37, 37)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField_student_field_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn_student_button_2)
                    .addComponent(searchType_student_combo_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jScrollPane5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        marksTable_teacher.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        marksTable_teacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Student No", "Subject Code", "Internal ", "External", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        marksTable_teacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marksTable_teacherMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(marksTable_teacher);
        if (marksTable_teacher.getColumnModel().getColumnCount() > 0) {
            marksTable_teacher.getColumnModel().getColumn(0).setPreferredWidth(50);
            marksTable_teacher.getColumnModel().getColumn(0).setMaxWidth(50);
            marksTable_teacher.getColumnModel().getColumn(1).setPreferredWidth(150);
            marksTable_teacher.getColumnModel().getColumn(1).setMaxWidth(150);
            marksTable_teacher.getColumnModel().getColumn(2).setPreferredWidth(100);
            marksTable_teacher.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout updateResultsCardPanelLayout = new javax.swing.GroupLayout(updateResultsCardPanel);
        updateResultsCardPanel.setLayout(updateResultsCardPanelLayout);
        updateResultsCardPanelLayout.setHorizontalGroup(
            updateResultsCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateResultsCardPanelLayout.createSequentialGroup()
                .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        updateResultsCardPanelLayout.setVerticalGroup(
            updateResultsCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateResultsCardPanelLayout.createSequentialGroup()
                .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 328, Short.MAX_VALUE))
        );

        rightSplitPanel.add(updateResultsCardPanel, "card_update_results");

        changePasswordCardPanel.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(53, 53, 1, 53));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Update Account Information");

        jLabel8.setText("Change Password");

        jLabel9.setText("Old Password");

        jLabel10.setText("New Password");

        saveBtn.setText("Save");

        jLabel11.setText("Confirm Password");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(oldPassField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(newPassField)
                                    .addComponent(confirmField)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(saveBtn))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7)))
                .addContainerGap(630, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(78, 78, 78)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(oldPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(confirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(saveBtn)
                .addContainerGap(555, Short.MAX_VALUE))
        );

        changePasswordCardPanel.add(jPanel4, java.awt.BorderLayout.CENTER);

        rightSplitPanel.add(changePasswordCardPanel, "card_change_password");

        informationCardPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lecNameLabel.setText("Fullname");

        jLabel3.setText("Username");

        jLabel4.setText("Year");

        jLabel5.setText("Subject");

        subjectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Subject Name", "Subject Code", "Semester"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(subjectsTable);
        if (subjectsTable.getColumnModel().getColumnCount() > 0) {
            subjectsTable.getColumnModel().getColumn(2).setResizable(false);
        }

        nameField.setEditable(false);

        usernameField.setEditable(false);

        yearField.setEditable(false);

        subjectField.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Subjects Taught");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Personal Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lecNameLabel)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(usernameField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subjectField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lecNameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subjectField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(368, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout informationCardPanelLayout = new javax.swing.GroupLayout(informationCardPanel);
        informationCardPanel.setLayout(informationCardPanelLayout);
        informationCardPanelLayout.setHorizontalGroup(
            informationCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        informationCardPanelLayout.setVerticalGroup(
            informationCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        rightSplitPanel.add(informationCardPanel, "card_more");
        informationCardPanel.getAccessibleContext().setAccessibleName("");

        jSplitPane1.setRightComponent(rightSplitPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.PAGE_START);

        jMenuBar1.setName("menuBar"); // NOI18N

        jMenu1.setText("File");

        signout_menu.setText("Sign Out");
        signout_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signout_menuActionPerformed(evt);
            }
        });
        jMenu1.add(signout_menu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setText("About us");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stSearchBtnActionPerformed
        // TODO add your handling code here:
       CardLayout card = (CardLayout)rightSplitPanel.getLayout();
    card.show(rightSplitPanel, "card_student_search");
    }//GEN-LAST:event_stSearchBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

        CardLayout card = (CardLayout)rightSplitPanel.getLayout();
        card.show(rightSplitPanel, "card_update_results");

        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void moreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreBtnActionPerformed

        CardLayout card = (CardLayout)rightSplitPanel.getLayout();
        card.show(rightSplitPanel, "card_more");
        
        ArrayList<String> teacherInfo = new DBConnect().getTeacherInfo(retrievedUsername);
        
        nameField.setText(teacherInfo.get(1));
        usernameField.setText(teacherInfo.get(2));
        yearField.setText(teacherInfo.get(3));
        subjectField.setText(teacherInfo.get(4));
        
       
        
        DefaultTableModel model = (DefaultTableModel) subjectsTable.getModel();
         DBConnect.TableData tableData = null;
       tableData = new DBConnect().searchSubject_by_code(teacherInfo.get(4));//where 4 is the subjet code
        Object[][] row = tableData.getcolData();
        System.out.println("" + tableData.getcolData().length + " columns and "+tableData.getRowCount()+" rows");
        for (int i = 0; i < tableData.getRowCount(); i++) {

            model.addRow(new Object[]{row[i][0], row[i][1], row[i][2], row[i][3]});
            System.out.println("added " + row[i][3]);
        }

    }//GEN-LAST:event_moreBtnActionPerformed

    private void accountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)rightSplitPanel.getLayout();
        card.show(rightSplitPanel, "card_change_password");
    }//GEN-LAST:event_accountBtnActionPerformed

    private void searchBtn_student_button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn_student_button_2ActionPerformed
       
         String searchType = searchType_student_combo_2.getSelectedItem().toString();
        String searchTerm = searchField_student_field_2.getText();
        
        DefaultTableModel model = (DefaultTableModel) marksTable_teacher.getModel();
        new DBConnect().deleteAllRows(model);
         DBConnect.TableData tableData = null;
        if (searchType.equals("Student No")) { //Student No, Subject Code  Student No, Subject Code
            
             tableData =   new DBConnect().studentMarks_by_enrol_no(searchTerm);
        } else if (searchType.equals("Subject Code")) {
            
             tableData =  new DBConnect().studentMarks_by_subject(searchTerm);
        } else {
            System.out.println("Error with marksTable_teacher search term");
        }
        
        Object[][] row = tableData.getcolData();
        System.out.println("" + tableData.getcolData().length + " columns and "+tableData.getRowCount()+" rows");
        for (int i = 0; i < tableData.getRowCount(); i++) {
            
            model.addRow(new Object[]{row[i][0], row[i][1], row[i][2], row[i][3], row[i][4], row[i][5]});
            System.out.println("added " + row[i][3]);
        }

       
    }//GEN-LAST:event_searchBtn_student_button_2ActionPerformed

    private void searchBtn_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn_studentActionPerformed
        String searchType = searchType_student.getSelectedItem().toString();
        String searchTerm = searchField_student.getText();
        
        DefaultTableModel model = (DefaultTableModel) studentSearchTable.getModel();
         new DBConnect().deleteAllRows(model);
         DBConnect.TableData tableData = null;
        if (searchType.equals("Student No")) { //Student No, Student Name
              tableData =   new DBConnect().studentInfo_by_enrol_no(searchTerm);
        } else if (searchType.equals("Student Name")) {
              tableData =  new DBConnect().studentInfo_by_name(searchTerm);
        } else {
            System.out.println("Error with studentSearchTable search term");
        }
        
        Object[][] row = tableData.getcolData();
        System.out.println("" + tableData.getcolData().length + " columns and "+tableData.getRowCount()+" rows");
        for (int i = 0; i < tableData.getRowCount(); i++) {
            //"#", "Fullname", "Student No", "Batch", "Address", "DOB"
            model.addRow(new Object[]{i+1, row[i][0], row[i][1], row[i][2], row[i][3], row[i][4]});
            System.out.println("added " + row[i][3]);
        }

    }//GEN-LAST:event_searchBtn_studentActionPerformed

    private void searchType_student_combo_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchType_student_combo_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchType_student_combo_2ActionPerformed

    private void externalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_externalFieldActionPerformed

    private void addMarksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMarksBtnActionPerformed
        errorMessage.setText("");
        
        String enrol = enrolNo_Field.getText();
        String internal = internalField.getText();
        String external = externalField.getText();
        String subcode = subjectCodeField.getText();
        int total = Integer.parseInt(internal) + Integer.parseInt(external);
        if(!enrol.equals("") && !internal.equals("") && !external.equals("") && !subcode.equals("")){
            
            DefaultTableModel model = (DefaultTableModel) marksTable_teacher.getModel();
            model.addRow(new Object[]{model.getRowCount()+1, enrol, subcode, internal, external, total});
           
            new DBConnect().addStudentMarks( enrol, internal, external, total, (total > 50), subcode);
        }else {
            errorMessage.setText("All Fields are required!");//All Fields are required!
        }
    }//GEN-LAST:event_addMarksBtnActionPerformed

    private void marksTable_teacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marksTable_teacherMouseClicked
        DefaultTableModel model = (DefaultTableModel) marksTable_teacher.getModel();
        enrolNo_Field.setText(model.getValueAt(marksTable_teacher.getSelectedRow(), 1).toString());
        internalField.setText(model.getValueAt(marksTable_teacher.getSelectedRow(), 3).toString());
        externalField.setText(model.getValueAt(marksTable_teacher.getSelectedRow(), 4).toString());
        subjectCodeField.setText(model.getValueAt(marksTable_teacher.getSelectedRow(), 2).toString());
        
    }//GEN-LAST:event_marksTable_teacherMouseClicked

    private void subjectCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectCodeFieldActionPerformed

    private void updateBtn_marksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn_marksActionPerformed
        errorMessage.setText("");
        
       
        int total = 0;
        DefaultTableModel model = (DefaultTableModel) marksTable_teacher.getModel();
        if (marksTable_teacher.getSelectedRow() != -1) {
            String enrol = enrolNo_Field.getText();
            String internal = internalField.getText();
            String external = externalField.getText();
            String subcode = subjectCodeField.getText();
            if(!enrol.equals("")){
            model.setValueAt(enrol, marksTable_teacher.getSelectedRow(), 1);
            model.setValueAt(internal, marksTable_teacher.getSelectedRow(), 3);
            model.setValueAt(external, marksTable_teacher.getSelectedRow(), 4);
            model.setValueAt(subcode, marksTable_teacher.getSelectedRow(), 2);
            total = Integer.parseInt(internal) + Integer.parseInt(external);
            model.setValueAt(total, marksTable_teacher.getSelectedRow(), 5);
            new DBConnect().updateStudentMarks(enrol, internal, external, total, (total > 49), subcode);
            }else {
             errorMessage.setText("All Fields must be filled.");
            }
        } else {
            if (marksTable_teacher.getRowCount() == 0) {
                errorMessage.setText("Search for a student first.");
            } else {
                errorMessage.setText("You must select a student.");
            }
        }
    }//GEN-LAST:event_updateBtn_marksActionPerformed

    private void signout_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signout_menuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_signout_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherLandingPage("lecturer").setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountBtn;
    private javax.swing.JButton addMarksBtn;
    private javax.swing.JPanel changePasswordCardPanel;
    private javax.swing.JPasswordField confirmField;
    private javax.swing.JTextField enrolNo_Field;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JTextField externalField;
    private javax.swing.JPanel informationCardPanel;
    private javax.swing.JTextField internalField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lecNameLabel;
    private javax.swing.JPanel leftSplitPanel;
    private javax.swing.JTable marksTable_teacher;
    private javax.swing.JButton moreBtn;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField newPassField;
    private javax.swing.JPasswordField oldPassField;
    private javax.swing.JPanel rightSplitPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn_student;
    private javax.swing.JButton searchBtn_student_button_2;
    private javax.swing.JTextField searchField_student;
    private javax.swing.JTextField searchField_student_field_2;
    private javax.swing.JComboBox searchType_student;
    private javax.swing.JComboBox searchType_student_combo_2;
    private javax.swing.JMenuItem signout_menu;
    private javax.swing.JLabel stAcTitle;
    private javax.swing.JLabel stAcTitle1;
    private javax.swing.JButton stSearchBtn;
    private javax.swing.JPanel stSearchCardPanel;
    private javax.swing.JTable studentSearchTable;
    private javax.swing.JTextField subjectCodeField;
    private javax.swing.JTextField subjectField;
    private javax.swing.JTable subjectsTable;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateBtn_marks;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JPanel updateResultsCardPanel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables

    private void populateMarksTable(String enrol_no) {
        DBConnect.TableData tableData =  new DBConnect().studentMarks_by_enrol_no(enrol_no);
                DefaultTableModel model = (DefaultTableModel) studentSearchTable.getModel();
                Object[][] row = tableData.getcolData();
                System.out.println(""+tableData.getcolData().length+" records");
                for(int i =0 ; i < tableData.getRowCount(); i ++){
                    
                    
                    model.addRow(new Object[]{row[i][0], row[i][1], row[i][2], row[i][3], row[i][4], row[i][5]});
                    System.out.println("added "+row[i][3]);
               }
    }
}
